name: Shellcheck
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run shellcheck
        run: shellcheck -s sh build.sh
